apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-targetallocator-sa
  namespace: observability
---
# https://github.com/open-telemetry/opentelemetry-operator/blob/main/cmd/otel-allocator/README.md#rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-targetallocator-clusterrole
  namespace: observability
rules:
  - apiGroups: 
      - monitoring.coreos.com
    resources:
      - servicemonitors
      - podmonitors
    verbs: ['*']
    
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/stats
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
    verbs: ["get"]

  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs: ["get", "list", "watch"]

  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]

  - nonResourceURLs:
      - /metrics
      # - /metrics/cadvisor
      # - /metrics/probes
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: opentelemetry-targetallocator-clusterrolebinding
  namespace: observability

subjects:
  - kind: ServiceAccount
    name: opentelemetry-targetallocator-sa
    apiGroup: ""

roleRef:
  kind: ClusterRole
  name: opentelemetry-targetallocator-clusterrole
  apiGroup: ""