apiVersion: v1
kind: ServiceAccount
metadata:
  name: spring-namespace-reader
  namespace: default
  # annotations:
  # In case your spring app need to access GCP resources you can set this annotation and link it with a GCP service account.
  # iam.gke.io/gcp-service-account: postgres-client@your-project.iam.gserviceaccount.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-reader
  namespace: default
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: spring-namespace-reader
  namespace: default

subjects:
  - kind: ServiceAccount
    name: spring-namespace-reader
    apiGroup: ""

roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""