apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector
metadata:
  name: otel-collector-metrics
  namespace: observability
spec:
  mode: deployment # statefulset is the only allowed mode with targetAllocator
  serviceAccount: collector-ta
  env:
    - name: GOMEMLIMIT
      value: 205MiB # should be 80% of memory limit

  # https://opentelemetry.io/docs/kubernetes/operator/target-allocator/
  # https://github.com/open-telemetry/opentelemetry-operator/blob/main/cmd/otel-allocator/README.md
  # Migration blocked, can not scrape all target because of https://github.com/open-telemetry/opentelemetry-operator/issues/1844
  # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspectargetallocator
  # targetAllocator:
  #   enabled: true
  #   serviceAccount: opentelemetry-targetallocator-sa
  #   prometheusCR:
  #     enabled: true
  #     serviceMonitorSelector:
  #       matchLabels:
  #         prometheus.io/scrap-with: otel-collector-metrics
  #     podMonitorSelector:
  #       matchLabels:
  #         prometheus.io/scrap-with: otel-collector-metrics
  #   resources:
  #     requests:
  #       memory: 256Mi
  #       cpu: 100m
  #     limits:
  #       memory: 256Mi
  #       cpu: 100m

  autoscaler:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilization: 80
    targetMemoryUtilization: 80

  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m

  # https://www.otelbin.io/
  config: |
    receivers:
      otlp:
        protocols:
          grpc: null

      prometheus:
        # trim_metric_suffixes: true # request_duration_seconds_total to be trimmed to request_duration
        config:
          scrape_configs:
            - job_name: otel-collector-metrics
              scrape_interval: 30s
              static_configs:
                - targets: 
                    - :8888

    exporters:
      debug:
        verbosity: detailed

      # Use this exporter if you want to send otlp metrics to prometheus.
      otlphttp/prometheus: 
        endpoint: http://kube-prometheus-stack-prometheus.observability:9090/api/v1/otlp
        tls:
          insecure: true

      prometheusremotewrite:
        endpoint: http://kube-prometheus-stack-prometheus.observability:9090/api/v1/write
        tls:
          insecure: true
        # Add k8sattributes to metric labels (be very carefull with quantity of labels, by default java agent sends lots of resource labels)
        resource_to_telemetry_conversion:
          enabled: true

    processors:
      batch:
        timeout: 200ms

      # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md
      k8sattributes:
        extract:
          labels:
            - from: pod
              key: app.kubernetes.io/component
              tag_name: component
            - from: pod
              key: app.kubernetes.io/application
              tag_name: application
          metadata:
            - k8s.node.name
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.pod.name
            - k8s.container.name
        passthrough: false
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

      # drop metrics if memory usage gets too high
      memory_limiter: 
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25

      resource:
        attributes:
          - key: collector.name
            value: otel-collector-metrics
            action: upsert

    extensions:
      health_check: null
      pprof: null
      zpages: null
      
    service:
      extensions: 
        - health_check
        - pprof
        - zpages

      telemetry:
        logs: null
          # encoding: json
          # level: debug
        metrics:
          address: :8888
          level: basic

      pipelines:
        metrics:
          receivers: 
            - prometheus
            - otlp
          processors: 
            - k8sattributes
            - metricstransform
            - resource
            - batch
            - memory_limiter
          exporters: 
            - prometheusremotewrite
            - debug