apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector
metadata:
  name: otel-collector-metrics
spec:
  mode: statefulset # Only allowed mode with targetAllocator
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
          env:

    - name: GOMEMLIMIT
      value: 205MiB # should be 80% of memory limit

  # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspectargetallocator
  # Migration blocked, can not scrape all target because of https://github.com/open-telemetry/opentelemetry-operator/issues/1844
  serviceAccount: opentelemetry-collector-sa
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-targetallocator-sa
    prometheusCR:
      enabled: true
      serviceMonitorSelector:
        matchLabels:
          prometheus.io/scrap-with: otel-collector-metrics
      podMonitorSelector:
        matchLabels:
          prometheus.io/scrap-with: otel-collector-metrics
    
    # resources:
    #   requests:
    #     memory: 256Mi
    #     cpu: 100m
    #   limits:
    #     memory: 256Mi
    #     cpu: 100m

  autoscaler:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilization: 80
    targetMemoryUtilization: 80

  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m


  # https://www.otelbin.io/
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318

      # Collect own metrics
      prometheus:
        trim_metric_suffixes: true
        config:
          scrape_configs:
            - job_name: 'otel-collector-traces'
              scrape_interval: 5s
              static_configs:
                - targets: ["${env:MY_POD_IP}:8888"]

    processors:
      k8sattributes:
      batch:
        timeout: 200ms
      # drop metrics if memory usage gets too high
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15

    resource:
      attributes:
        - key: otel.provider
          value: otel-collector-metrics
          action: insert

    exporters:
      debug:

      # Use this exporter if you want to send otlp metrics to prometheus.
      # otlphttp/prometheus:
      #   endpoint: http://kube-prometheus-stack-prometheus.observability:9090/api/v1/otlp
      #   tls:
      #     insecure: true

      prometheusremotewrite:
        endpoint: http://kube-prometheus-stack-prometheus.observability:9090/api/v1/write
        tls:
          insecure: true

    # add healthcheck, debugging port and pprof endpoints
    extensions: [health_check, zpages, pprof]
      
    service:
      # expose collector metrics on port 8888
      telemetry:
        metrics:
          # level: detailed
          address: ${env:MY_POD_IP}:8888
      
      # add healthcheck, debugging port and pprof endpoints
      extensions: [health_check, zpages, pprof]
      
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [k8sattributes, batch, memory_limiter]
          exporters: [prometheusremotewrite, debug]