apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-metrics
spec:
  mode: statefulset # Only allowed mode with targetAllocator

  # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspectargetallocator
  # Migration blocked, can not scrape all target because of https://github.com/open-telemetry/opentelemetry-operator/issues/1844
  targetAllocator:
    enabled: true
    serviceAccount: opentelemetry-targetallocator-sa
    prometheusCR:
      enabled: true
      # serviceMonitorSelector:
      #   matchLabels:
      #     release: prometheus
      # podMonitorSelector:
      #   matchLabels:
      #     release: prometheus
    # resources:
    replicas: 1

  serviceAccount: opentelemetry-collector-sa
  config: |
    receivers:
      # otlp:
      #   protocols:
      #     grpc:
      
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector-metrics'
              scrape_interval: 10s
              static_configs:
                - targets: ['otel-collector-metrics-collector-monitoring:8888']
        target_allocator:
          endpoint: otel-collector-targetallocator
          interval: 30s
          collector_id: "${POD_NAME}"

    processors:
      batch:

    exporters:
      debug:

      prometheusremotewrite:
        endpoint: kube-prometheus.observability:9090/api/v1/write
        tls:
          insecure: true
      # otlp:
      #   endpoint: tempo.observability:4317
      #   tls:
      #     insecure: true
          

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        # traces:
        #   receivers: [otlp]
        #   processors: [batch]
        #   exporters: [debug, otlp]
        metrics:
          receivers: [prometheus]
          processors: [batch]
          exporters: [prometheusremotewrite]