apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector
metadata:
  name: otel-collector-metrics
  namespace: observability
spec:
  mode: deployment # statefulset is the only allowed mode with targetAllocator
  serviceAccount: collector-ta
  env:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: GOMEMLIMIT
      value: 205MiB # should be 80% of memory limit

  # https://opentelemetry.io/docs/kubernetes/operator/target-allocator/
  # https://github.com/open-telemetry/opentelemetry-operator/blob/main/cmd/otel-allocator/README.md
  # Migration blocked, can not scrape all target because of https://github.com/open-telemetry/opentelemetry-operator/issues/1844
  # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollectorspectargetallocator
  # targetAllocator:
  #   enabled: true
  #   serviceAccount: opentelemetry-targetallocator-sa
  #   prometheusCR:
  #     enabled: true
  #     serviceMonitorSelector:
  #       matchLabels:
  #         prometheus.io/scrap-with: otel-collector-metrics
  #     podMonitorSelector:
  #       matchLabels:
  #         prometheus.io/scrap-with: otel-collector-metrics
  #   resources:
  #     requests:
  #       memory: 256Mi
  #       cpu: 100m
  #     limits:
  #       memory: 256Mi
  #       cpu: 100m

  autoscaler:
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilization: 80
    targetMemoryUtilization: 80

  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 200m

  # https://www.otelbin.io/
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317

      prometheus:
        # trim_metric_suffixes: true # request_duration_seconds_total to be trimmed to request_duration
        config:
          scrape_configs:
            - job_name: otel-collector-metrics
              scrape_interval: 30s
              static_configs:
                - targets: 
                    - ${env:MY_POD_IP}:8888

    exporters:
      debug:
        verbosity: detailed

      # Use this exporter if you want to send otlp metrics to prometheus.
      # https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/otlphttpexporter/README.md
      otlphttp/prometheus: 
        endpoint: http://kube-prometheus-stack-prometheus.observability:9090/api/v1/otlp
        tls:
          insecure: true

      # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/prometheusremotewriteexporter/README.md
      prometheusremotewrite:
        endpoint: http://kube-prometheus-stack-prometheus.observability:9090/api/v1/write
        tls:
          insecure: true
        # Add k8sattributes to metric labels (be very carefull with quantity of labels, by default java agent sends lots of resource labels)
        resource_to_telemetry_conversion:
          enabled: true

    processors:
      # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/batchprocessor/README.md
      batch:
        send_batch_size: 8192
        send_batch_max_size: 8192
        timeout: 5s

      # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/k8sattributesprocessor/README.md
      k8sattributes:
        extract:
          labels:
            - from: pod
              key: app.kubernetes.io/component
              tag_name: component
            - from: pod
              key: app.kubernetes.io/application
              tag_name: application
          metadata:
            - k8s.node.name
            - k8s.namespace.name
            - k8s.deployment.name
            - k8s.statefulset.name
            - k8s.daemonset.name
            - k8s.cronjob.name
            - k8s.job.name
            - k8s.pod.name
            - k8s.container.name
            - k8s.pod.uid
            - k8s.pod.start_time
        passthrough: false
        pod_association:
          - sources:
              - from: resource_attribute
                name: k8s.pod.ip
          - sources:
              - from: resource_attribute
                name: k8s.pod.uid
          - sources:
              - from: connection

      # drop metrics if memory usage gets too high
      # https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/memorylimiterprocessor/README.md
      memory_limiter: 
        check_interval: 1s
        limit_percentage: 65
        spike_limit_percentage: 20

      resource:
        attributes:
          - action: upsert
            key: collector.name
            value: otel-collector-metrics
          # We need to add the pod IP as a resource label so the k8s attributes processor can find it.
          - action: insert
            key: k8s.pod.ip
            value: ${env:MY_POD_IP}

    # resourcedetection:
    #   detectors: [gcp]
    #   timeout: 10s

    extensions:
      health_check:
      pprof:
      zpages:
      
    service:
      extensions: 
        - health_check
        - pprof
        - zpages

      telemetry:
        logs:
          # encoding: json
          # level: debug
        metrics:
          address: ${env:MY_POD_IP}:8888

      pipelines:
        metrics:
          receivers: 
            - prometheus
            - otlp
          processors: 
            - k8sattributes
            - resource
            - memory_limiter
            - batch
          exporters: 
            - prometheusremotewrite
            - debug