apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-traces
spec:
  # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md
  mode: deployment
  env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
  config: |
    receivers:

      otlp:
        protocols:
          grpc:

      # Collect own metrics
      prometheus:
        config:
          scrape_configs:
            - job_name: 'otel-collector-traces'
              scrape_interval: 5s
              static_configs:
                - targets: ['${POD_IP}:8888']

    processors:
      batch:

    exporters:
      debug:
      otlp:
        endpoint: tempo.observability:4317
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: kube-prometheus.observability:9090/api/v1/write
        tls:
          insecure: true
        remote_write_queue:
          enabled: false

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [prometheus]
          # processors: [batch]
          exporters: [prometheusremotewrite, debug]

      # telemetry:
      #     logs:
      #       level: "debug"