apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-traces
spec:
  mode: deployment
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

    processors:
      batch:

    exporters:
      debug:
      otlp:
        endpoint: tempo.observability:4317
        tls:
          insecure: true
      prometheusremotewrite:
        endpoint: kube-prometheus.observability:9090/api/v1/write
        tls:
          insecure: true
        remote_write_queue:
          enabled: true
          queue_size: 100

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [otlp]
          # processors: [batch]
          exporters: [prometheusremotewrite]

      # telemetry:
      #     logs:
      #       level: "debug"