apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector-traces
spec:
  # https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md
  mode: deployment
  env:
    - name: POD_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.podIP
  config: |
    receivers:
      otlp:
        protocols:
          grpc:

      prometheus: # Collect own metrics
        config:
          scrape_configs:
            - job_name: 'otel-collector-traces'
              scrape_interval: 5s
              static_configs:
                - targets: ["${env:POD_IP}:8888"]

    processors:
      batch:

    exporters:
      debug:
      logging:

      otlp:
        endpoint: tempo.observability:4317
        tls:
          insecure: true

      otlphttp/prometheus:
        endpoint: http://kube-prometheus.observability:9090/api/v1/otlp
        tls:
          insecure: true

      prometheusremotewrite:
        endpoint: http://kube-prometheus.observability:9090/api/v1/write
        tls:
          insecure: true

    extensions:
      health_check:
      pprof:
      zpages:

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp]
        metrics:
          receivers: [prometheus]
          # processors: [batch]
          exporters: [prometheusremotewrite, debug]

      telemetry:
        metrics:
          address: ${env:POD_IP}:8888