apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-collector-sa
  namespace: observability
---
# https://github.com/open-telemetry/opentelemetry-operator/blob/main/cmd/otel-allocator/README.md#rbac
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opentelemetry-collector-clusterrole
  namespace: observability
rules:
  - apiGroups: [""]
    resources:
    - nodes
    - nodes/metrics
    - services
    - endpoints
    - pods
    - namespaces
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources:
    - configmaps
    verbs: ["get"]

  - apiGroups:
    - discovery.k8s.io
    resources:
    - endpointslices
    verbs: ["get", "list", "watch"]

  - apiGroups:
    - networking.k8s.io
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]

  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

  - apiGroups:
    - monitoring.coreos.com
    resources:
    - servicemonitors
    - podmonitors
    verbs:
    - '*'
    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: opentelemetry-collector-clusterrolebinding
  namespace: observability

subjects:
  - kind: ServiceAccount
    name: opentelemetry-collector-sa
    apiGroup: ""

roleRef:
  kind: ClusterRole
  name: opentelemetry-collector-clusterrole
  apiGroup: ""