apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-opentelemetry-operator-helm
  namespace: argocd

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true

  sources:
    - chart: opentelemetry-operator
      repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.49.1

      # https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator
      
      # https://opentelemetry.io/docs/kubernetes/operator/target-allocator/
      # https://github.com/open-telemetry/opentelemetry-operator/blob/main/cmd/otel-allocator/README.md
      helm:
        valuesObject:
          fullnameOverride: opentelemetry-operator

    - repoURL: ${ARGOCD_ENV_GITHUB_REPO}/argo-deploy-applications-observability.git
      targetRevision: main
      path: applications/overlays/local/otel-collector-traces-app

    # - repoURL: ${ARGOCD_ENV_GITHUB_REPO}/argo-deploy-applications-observability.git
    #   targetRevision: main
    #   path: applications/overlays/local/otel-collector-metrics-app

  destination:
    server: "https://kubernetes.default.svc"
    namespace: observability


