{
 "title": "Applications",
 "description": "Dashboard for Keycloak",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Application",
    "query": "label_values(keycloak_logins_total, container)"
   },
   {
    "name": "realm",
    "label": "Realm",
    "query": "label_values(keycloak_logins_total{container=\"$container\", provider=\"keycloak\"}, realm)"
   },
   {
    "name": "client_id",
    "label": "client_id",
    "query": "label_values(keycloak_logins_total{container=\"$container\", provider=\"keycloak\", realm=~\"$realm\"}, client_id)"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{container=\"$container\", area=\"heap\"})*100/sum(jvm_memory_bytes_max{container=\"$container\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "description": "Memory currently being used by Keycloak.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{container=\"$container\", area=\"nonheap\"})*100/sum(jvm_memory_bytes_max{container=\"$container\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_max{container=\"$container\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "sum(jvm_memory_bytes_committed{container=\"$container\"})",
     "legendFormat": "Comitted"
    },
    {
     "expr": "sum(jvm_memory_bytes_used{container=\"$container\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Logins Per REALM",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(keycloak_logins_total{container=\"$container\"}) by (realm)",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Logins Per CLIENT",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 10, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(keycloak_logins_total{container=\"$container\"}) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registrations Per CLIENT",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(keycloak_registrations{container=\"$container\"}) by (client_id)",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Logins per REALM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (realm)(increase(keycloak_logins_total{container=\"$container\"}[1h]))",
     "legendFormat": "{{realm}}"
    }
   ]
  },
  {
   "title": "Login Errors on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(keycloak_failed_login_attempts_total{container=\"$container\", provider=\"keycloak\", realm=~\"$realm\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Logins per CLIENT on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(keycloak_logins_total{container=\"$container\", realm=~\"$realm\", provider=\"keycloak\"}[1h])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Login Errors for $client_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(keycloak_failed_login_attempts_total{container=\"$container\", provider=\"keycloak\", realm=~\"$realm\", client_id=~\"$client_id\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  },
  {
   "title": "Registrations per CLIENT on realm $realm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(keycloak_registrations{container=\"$container\", realm=~\"$realm\", provider=\"keycloak\"}[1h])",
     "legendFormat": "{{client_id}}"
    }
   ]
  },
  {
   "title": "Registration Errors for $client_id",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(keycloak_registrations_errors{container=\"$container\", provider=\"keycloak\", realm=~\"$realm\", client_id=~\"$client_id\"}[1h])",
     "legendFormat": "{{error}}"
    }
   ]
  }
 ]
}